### ISSUE TITLE
Groundwork and repository setup

### ISSUE THREAD

**Issue by lukasz-zimnoch** [threshold-network/bitcoin-on-base#1]
This issue is about setting up the repository for development and doing all necessary groundwork to trigger the work on the Bitcoin on Base dApp. 

The idea is to use the existing codebase of the [Threshold Dashboard](https://github.com/threshold-network/token-dashboard) as a jump pad. The groundwork phase can be approached twofold:
1. Start with fresh Bitcoin on Base repository and selectively pick up specific cross-cutting components from the Threshold Dashboard codebase
2. Initiate Bitcoin on Base repository as Threshold Dashboard's fork and cleanup unnecessary components.

Once this issue is addressed, this repository should be ready to build the Bitcoin on Base interface and features required for the MVP.
```[tasklist]
### Tasks
- [ ] https://github.com/threshold-network/bitcoin-on-base/pull/7
- [ ] https://github.com/threshold-network/bitcoin-on-base/pull/8
- [ ] https://github.com/threshold-network/bitcoin-on-base/pull/10
- [ ] https://github.com/threshold-network/bitcoin-on-base/pull/11
- [ ] https://github.com/threshold-network/bitcoin-on-base/pull/12
- [ ] https://github.com/threshold-network/bitcoin-on-base/pull/25
- [ ] https://github.com/threshold-network/bitcoin-on-base/pull/26
- [ ] https://github.com/threshold-network/bitcoin-on-base/pull/27
- [ ] https://github.com/threshold-network/bitcoin-on-base/pull/28
```

TODO (by @michalsmiarowski):
- [x] Remove Upgrade page and every component/logic that is used only there
- [x] Remove Overview page and every component/logic that is used only there
- [x] Remove Staking page and every component/logic that is used only there
- [x] Remove Feedback page and every component/logic that is used only there
- [x] Remove any leftovers from the PRs above
- [x] Remove remaining unnecessary stuff (e.g. Storybook)
- [ ] ~~Configure CI~~ (Moved to separate task: #23)
