### ISSUE TITLE
MVP: Initial landing page

### ISSUE THREAD

**Issue by lukasz-zimnoch** [threshold-network/bitcoin-on-base#2]
This issue is about creating an initial landing page for the MVP. 

The main component of the landing page should be a form allowing the user to bridge Bitcoin to Base. The form should have a field allowing the user to put the BTC address for deposit recovery (**BTC Recovery Address**), and a read-only field displaying the user's Base address fetched from the connected wallet (**Base Address**). The initial page should also contain a placeholder for displaying the user's tBTC balance already bridged to Base (**My Balance**). 

The whole UI should be implemented in accordance with [Sorin's design](https://www.figma.com/file/OUdSfHsmgV8EJpWxAzXjl5/Design-Tasks?type=design&node-id=4350-108652&mode=design&t=qCCMmnTiP3lPc7ZL-0).

The scope of this task includes just the UI part. It does not include interactions with the wallet and contracts layer. All data should be mocked.
```[tasklist]
### Tasks
- [ ] https://github.com/threshold-network/bitcoin-on-base/pull/13
- [ ] https://github.com/threshold-network/bitcoin-on-base/pull/15
- [ ] https://github.com/threshold-network/bitcoin-on-base/pull/17
- [ ] https://github.com/threshold-network/bitcoin-on-base/pull/19
- [ ] https://github.com/threshold-network/bitcoin-on-base/pull/20
- [ ] https://github.com/threshold-network/bitcoin-on-base/pull/30
```
