### ISSUE TITLE
MVP: Initiate bridging action

### ISSUE THREAD

**Issue by lukasz-zimnoch** [threshold-network/bitcoin-on-base#5]
This task is about implementing the action allowing to initiate bridging.

Once the user sends a BTC transaction to the generated deposit address, the application must detect this fact and initiate bridging. The user must attest to this action by signing a Base transaction using the connected wallet. Once done, the application must display a success message. After the bridging process is completed, the **My Balance** section must reflect that fact.

Specific UI/UX regarding this action must be agreed product and design-wise first.

If the contract layer and SDK are not ready to support this action yet, mock components can be used as temporary workaround.
```[tasklist]
### Tasks
- [ ] https://github.com/threshold-network/bitcoin-on-base/pull/22
- [ ] https://github.com/threshold-network/bitcoin-on-base/pull/18
- [ ] https://github.com/threshold-network/bitcoin-on-base/pull/37
- [ ] https://github.com/threshold-network/bitcoin-on-base/pull/45
```
